name: flash_chat
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.6
  animated_text_kit: ^4.2.2
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.3.0
  modal_progress_hud_nsn: ^0.5.1
  flutter_bloc: ^8.1.6
  auto_scroll: ^0.2.0
  formz: ^0.7.0
  equatable: ^2.0.0
  gradient_slide_to_act: ^0.0.2
  slidable_button: ^3.0.0+1
  image_picker: ^1.1.2
  firebase_storage: ^12.2.0
  form_validator: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
      - images/logo.png
      - images/default_avatar.jpg
